#!/usr/bin/env bash
# scripts/deploy.sh — Fresh deploy of The Rooms on a VPS that already runs other sites.
# Safe: only touches /opt/therooms, adds one nginx drop-in, starts rooms-* PM2 apps.
# Existing PM2 apps and nginx server blocks are NOT modified.
#
# Run as the non-root user that owns /opt/therooms (e.g. ubuntu / deploy).
# Requires: git, node ≥20, pnpm, pm2, docker, certbot already installed.
#
# Usage:
#   chmod +x scripts/deploy.sh
#   DATABASE_URL="..." POSTGRES_PASSWORD="..." ... bash scripts/deploy.sh

set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[deploy]${NC} $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }
error() { echo -e "${RED}[error]${NC} $*"; exit 1; }

DEPLOY_DIR="/opt/therooms"

# ── 0. Guard: required env vars ───────────────────────────────────────────────
info "Checking required environment variables..."
required=(
  DATABASE_URL
  POSTGRES_USER
  POSTGRES_PASSWORD
  MINIO_ROOT_USER
  MINIO_ROOT_PASSWORD
  NEXTAUTH_SECRET
  RESEND_API_KEY
)
missing=()
for v in "${required[@]}"; do
  [[ -z "${!v:-}" ]] && missing+=("$v")
done
if [[ ${#missing[@]} -gt 0 ]]; then
  error "Missing env vars: ${missing[*]}\nSet them before running this script."
fi

# ── 1. Ensure pnpm is available ───────────────────────────────────────────────
if ! command -v pnpm &>/dev/null; then
  info "Installing pnpm..."
  npm install -g pnpm@11.4.0
fi
pnpm --version

# ── 2. Clone or update the repo ──────────────────────────────────────────────
if [[ -d "$DEPLOY_DIR/.git" ]]; then
  info "Repo already exists — pulling latest..."
  git -C "$DEPLOY_DIR" pull
else
  info "Cloning repo to $DEPLOY_DIR..."
  # Replace with your actual repo URL
  git clone https://github.com/YOUR_ORG/the-rooms.git "$DEPLOY_DIR"
fi
cd "$DEPLOY_DIR"

# ── 3. Write .env if it does not exist ───────────────────────────────────────
if [[ ! -f "$DEPLOY_DIR/.env" ]]; then
  info "Writing .env from environment variables..."
  cat > "$DEPLOY_DIR/.env" <<EOF
# Auto-generated by deploy.sh — edit to add optional vars
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=${DATABASE_URL}

MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL:-https://minio.therooms.in}

REDIS_URL=${REDIS_URL:-redis://localhost:6379}

NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=https://therooms.in

RESEND_API_KEY=${RESEND_API_KEY}
RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL:-noreply@therooms.in}

IDFC_MERCHANT_ID=${IDFC_MERCHANT_ID:-}
IDFC_API_KEY=${IDFC_API_KEY:-}
IDFC_WEBHOOK_SECRET=${IDFC_WEBHOOK_SECRET:-}
EOF
  chmod 600 "$DEPLOY_DIR/.env"
  info ".env written (chmod 600)"
else
  warn ".env already exists — skipping write. Verify it has all required vars."
fi

# Source .env so docker-compose and prisma can see the vars in this shell
set -a; source "$DEPLOY_DIR/.env"; set +a

# ── 4. Create log directory ───────────────────────────────────────────────────
sudo mkdir -p /var/log/therooms
sudo chown -R "$USER:$USER" /var/log/therooms
info "Log directory: /var/log/therooms"

# ── 5. Start data services (Postgres, Redis, MinIO) — NOT nginx ──────────────
info "Starting data services (postgres, redis, minio)..."
# The nginx service has profile=standalone-nginx so it is excluded here.
docker compose up -d postgres redis minio minio-init

info "Waiting for Postgres to be ready..."
for i in {1..30}; do
  docker compose exec -T postgres pg_isready -U "${POSTGRES_USER:-therooms}" && break
  echo "  attempt $i/30..."
  sleep 3
done
docker compose exec -T postgres pg_isready -U "${POSTGRES_USER:-therooms}" \
  || error "Postgres did not become ready in time."

# ── 6. Install Node dependencies ─────────────────────────────────────────────
info "Installing dependencies (pnpm install --frozen-lockfile)..."
pnpm install --frozen-lockfile

# ── 7. Run Prisma migrations ──────────────────────────────────────────────────
info "Running database migrations..."
pnpm --filter @the-rooms/db exec prisma migrate deploy

# ── 8. Seed initial data (only on first deploy — idempotent) ─────────────────
info "Seeding database..."
pnpm --filter @the-rooms/db db:seed || warn "Seed returned non-zero — may already be seeded, continuing."

# ── 9. Build all apps ─────────────────────────────────────────────────────────
info "Building all apps (this takes a few minutes)..."
pnpm build

# ── 10. Start / reload PM2 apps ───────────────────────────────────────────────
info "Starting The Rooms apps in PM2..."
# Only delete rooms-* apps — existing unrelated PM2 processes are untouched.
for app in rooms-web rooms-guest rooms-front-office rooms-admin rooms-super-admin; do
  pm2 delete "$app" 2>/dev/null && info "  Removed old PM2 process: $app" || true
done

# Load env into PM2 environment before starting
pm2 start ecosystem.config.js

pm2 save
info "PM2 processes saved."

# Set up pm2 startup if not already done
if ! pm2 startup | grep -q "already"; then
  info "Configuring PM2 startup on boot..."
  pm2 startup | tail -1 | bash || warn "pm2 startup command failed — run manually: pm2 startup"
fi

# ── 11. Install nginx drop-in (does NOT restart existing sites) ───────────────
info "Installing nginx config..."
sudo cp "$DEPLOY_DIR/nginx/conf.d/the-rooms.conf" /etc/nginx/conf.d/the-rooms.conf

info "Testing nginx config..."
sudo nginx -t || error "nginx -t failed — fix the config before reloading."

# nginx -s reload does a graceful reload; existing connections are not dropped.
sudo nginx -s reload
info "nginx reloaded (existing sites untouched)."

# ── 12. SSL certificates ──────────────────────────────────────────────────────
info "Obtaining SSL certificates via certbot..."
warn "Certbot will serve ACME challenges over port 80. Ensure DNS A records for all"
warn "subdomains point to this VPS before proceeding."
echo ""

DOMAINS=(
  "therooms.in -d www.therooms.in"
  "my.therooms.in"
  "fo.therooms.in"
  "admin.therooms.in"
  "superadmin.therooms.in"
)

for d in "${DOMAINS[@]}"; do
  primary=$(echo "$d" | awk '{print $1}')
  if [[ -d "/etc/letsencrypt/live/$primary" ]]; then
    info "  Certificate already exists for $primary — skipping."
  else
    info "  Requesting certificate for $primary..."
    sudo certbot --nginx --non-interactive --agree-tos \
      --email "${CERTBOT_EMAIL:-admin@therooms.in}" \
      -d $d || warn "  certbot failed for $primary — check DNS and retry manually."
  fi
done

sudo nginx -s reload

# ── 13. Final status ──────────────────────────────────────────────────────────
echo ""
info "=== Deployment complete ==="
echo ""
pm2 status
echo ""
docker compose ps
echo ""
info "Test each portal:"
info "  curl -I https://therooms.in/health"
info "  curl -I https://my.therooms.in"
info "  curl -I https://fo.therooms.in"
info "  curl -I https://admin.therooms.in"
info "  curl -I https://superadmin.therooms.in"
echo ""
info "Create the first admin user:"
info "  DATABASE_URL=\$DATABASE_URL npx tsx packages/auth/scripts/create-user.ts \\"
info "    --email admin@therooms.in --name 'Admin' --role ADMIN --password 'YourPass@123'"
